name: feminae
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_screenutil: ^0.5.3
  firebase_core: ^0.4.3+2
  firebase_auth: ^0.15.3+1
  cloud_firestore: ^0.13.0+1
  flutter_icons: ^1.0.0+1
  flutter_svg: ^0.14.4
  progress_dialog: ^1.2.0
  flutter_widgets: ^0.1.9
  carousel_slider: ^1.4.1
  geolocator: ^5.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
  - images/

  fonts: 
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway-LightItalic.ttf
          weight: 300
          style: italic
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500      
   
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf

    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf

    - family: Poppins-Bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts: 
        - asset: fonts/Poppins-Medium.ttf